import 'package:flutter/material.dart';
import 'package:flutter_adaptive/flutter_adaptive.dart';

class MaterialIcons extends AdaptiveBundle {
  MaterialIcons()
      : super(
          builders: {
            MaterialIconBuilder(AdaptiveIcons.share, Icons.share),
            MaterialIconBuilder(AdaptiveIcons.book, Icons.book),
            MaterialIconBuilder(AdaptiveIcons.bookmark, Icons.bookmark),
            MaterialIconBuilder(AdaptiveIcons.info, Icons.info),
            MaterialIconBuilder(AdaptiveIcons.reply, Icons.reply),
            MaterialIconBuilder(AdaptiveIcons.flag, Icons.flag),
            MaterialIconBuilder(AdaptiveIcons.search, Icons.search),
            MaterialIconBuilder(AdaptiveIcons.circle, Icons.circle),
            MaterialIconBuilder(AdaptiveIcons.forward, Icons.forward),
            MaterialIconBuilder(AdaptiveIcons.home, Icons.home),
            MaterialIconBuilder(
                AdaptiveIcons.shopping_cart, Icons.shopping_cart),
            MaterialIconBuilder(AdaptiveIcons.phone, Icons.phone),
            MaterialIconBuilder(AdaptiveIcons.battery_full, Icons.battery_full),
            MaterialIconBuilder(AdaptiveIcons.bluetooth, Icons.bluetooth),
            MaterialIconBuilder(AdaptiveIcons.reply_all, Icons.reply_all),
            MaterialIconBuilder(AdaptiveIcons.shuffle, Icons.shuffle),
            MaterialIconBuilder(AdaptiveIcons.photo_camera, Icons.photo_camera),
            MaterialIconBuilder(
                AdaptiveIcons.switch_camera, Icons.switch_camera),
            MaterialIconBuilder(AdaptiveIcons.collections, Icons.collections),
            MaterialIconBuilder(AdaptiveIcons.folder, Icons.folder),
            MaterialIconBuilder(AdaptiveIcons.folder_open, Icons.folder_open),
            MaterialIconBuilder(AdaptiveIcons.delete, Icons.delete),
            MaterialIconBuilder(AdaptiveIcons.create, Icons.create),
            MaterialIconBuilder(AdaptiveIcons.refresh, Icons.refresh),
            MaterialIconBuilder(AdaptiveIcons.clear, Icons.clear),
            MaterialIconBuilder(AdaptiveIcons.add, Icons.add),
            MaterialIconBuilder(AdaptiveIcons.settings, Icons.settings),
            MaterialIconBuilder(AdaptiveIcons.music_note, Icons.music_note),
            MaterialIconBuilder(AdaptiveIcons.play_arrow, Icons.play_arrow),
            MaterialIconBuilder(AdaptiveIcons.pause, Icons.pause),
            MaterialIconBuilder(AdaptiveIcons.loop, Icons.loop),
            MaterialIconBuilder(AdaptiveIcons.volume_down, Icons.volume_down),
            MaterialIconBuilder(AdaptiveIcons.volume_mute, Icons.volume_mute),
            MaterialIconBuilder(AdaptiveIcons.volume_off, Icons.volume_off),
            MaterialIconBuilder(AdaptiveIcons.volume_up, Icons.volume_up),
            MaterialIconBuilder(AdaptiveIcons.fullscreen, Icons.fullscreen),
            MaterialIconBuilder(
                AdaptiveIcons.fullscreen_exit, Icons.fullscreen_exit),
            MaterialIconBuilder(AdaptiveIcons.mic_off, Icons.mic_off),
            MaterialIconBuilder(AdaptiveIcons.mic, Icons.mic),
            MaterialIconBuilder(AdaptiveIcons.person, Icons.person),
            MaterialIconBuilder(AdaptiveIcons.person_add, Icons.person_add),
            MaterialIconBuilder(AdaptiveIcons.group, Icons.group),
            MaterialIconBuilder(AdaptiveIcons.mail, Icons.mail),
            MaterialIconBuilder(AdaptiveIcons.tag, Icons.tag),
            MaterialIconBuilder(AdaptiveIcons.alarm, Icons.alarm),
            MaterialIconBuilder(AdaptiveIcons.arrow_left, Icons.arrow_left),
            MaterialIconBuilder(AdaptiveIcons.arrow_right, Icons.arrow_right),
            MaterialIconBuilder(AdaptiveIcons.bolt, Icons.bolt),
            MaterialIconBuilder(
                AdaptiveIcons.calendar_today, Icons.calendar_today),
            MaterialIconBuilder(AdaptiveIcons.camera, Icons.camera),
            MaterialIconBuilder(AdaptiveIcons.chat_bubble, Icons.chat_bubble),
            MaterialIconBuilder(AdaptiveIcons.chevron_left, Icons.chevron_left),
            MaterialIconBuilder(
                AdaptiveIcons.chevron_right, Icons.chevron_right),
            MaterialIconBuilder(AdaptiveIcons.cloud, Icons.cloud),
            MaterialIconBuilder(
                AdaptiveIcons.cloud_download, Icons.cloud_download),
            MaterialIconBuilder(AdaptiveIcons.cloud_upload, Icons.cloud_upload),
            MaterialIconBuilder(AdaptiveIcons.crop, Icons.crop),
            MaterialIconBuilder(AdaptiveIcons.crop_rotate, Icons.crop_rotate),
            MaterialIconBuilder(AdaptiveIcons.eject, Icons.eject),
            MaterialIconBuilder(AdaptiveIcons.flag_circle, Icons.flag_circle),
            MaterialIconBuilder(AdaptiveIcons.headphones, Icons.headphones),
            MaterialIconBuilder(AdaptiveIcons.hexagon, Icons.hexagon),
            MaterialIconBuilder(AdaptiveIcons.house, Icons.house),
            MaterialIconBuilder(AdaptiveIcons.keyboard, Icons.keyboard),
            MaterialIconBuilder(AdaptiveIcons.layers, Icons.layers),
            MaterialIconBuilder(AdaptiveIcons.lightbulb, Icons.lightbulb),
            MaterialIconBuilder(AdaptiveIcons.link, Icons.link),
            MaterialIconBuilder(AdaptiveIcons.lock, Icons.lock),
            MaterialIconBuilder(AdaptiveIcons.lock_open, Icons.lock_open),
            MaterialIconBuilder(AdaptiveIcons.map, Icons.map),
            MaterialIconBuilder(AdaptiveIcons.pause_circle, Icons.pause_circle),
            MaterialIconBuilder(AdaptiveIcons.percent, Icons.percent),
            MaterialIconBuilder(AdaptiveIcons.person_2, Icons.person_2),
            MaterialIconBuilder(AdaptiveIcons.person_3, Icons.person_3),
            MaterialIconBuilder(AdaptiveIcons.photo, Icons.photo),
            MaterialIconBuilder(AdaptiveIcons.piano, Icons.piano),
            MaterialIconBuilder(AdaptiveIcons.pin, Icons.pin),
            MaterialIconBuilder(AdaptiveIcons.play_circle, Icons.play_circle),
            MaterialIconBuilder(
                AdaptiveIcons.play_circle_fill, Icons.play_circle_fill),
            MaterialIconBuilder(AdaptiveIcons.power, Icons.power),
            MaterialIconBuilder(AdaptiveIcons.rectangle, Icons.rectangle),
            MaterialIconBuilder(AdaptiveIcons.repeat, Icons.repeat),
            MaterialIconBuilder(AdaptiveIcons.rocket, Icons.rocket),
            MaterialIconBuilder(AdaptiveIcons.rotate_left, Icons.rotate_left),
            MaterialIconBuilder(AdaptiveIcons.rotate_right, Icons.rotate_right),
            MaterialIconBuilder(AdaptiveIcons.shield, Icons.shield),
            MaterialIconBuilder(AdaptiveIcons.speaker, Icons.speaker),
            MaterialIconBuilder(AdaptiveIcons.square, Icons.square),
            MaterialIconBuilder(AdaptiveIcons.star, Icons.star),
            MaterialIconBuilder(AdaptiveIcons.stop, Icons.stop),
            MaterialIconBuilder(AdaptiveIcons.stop_circle, Icons.stop_circle),
            MaterialIconBuilder(AdaptiveIcons.timelapse, Icons.timelapse),
            MaterialIconBuilder(AdaptiveIcons.timer, Icons.timer),
            MaterialIconBuilder(AdaptiveIcons.today, Icons.today),
            MaterialIconBuilder(AdaptiveIcons.tornado, Icons.tornado),
            MaterialIconBuilder(AdaptiveIcons.tv, Icons.tv),
            MaterialIconBuilder(AdaptiveIcons.umbrella, Icons.umbrella),
            MaterialIconBuilder(AdaptiveIcons.videocam, Icons.videocam),
            MaterialIconBuilder(AdaptiveIcons.wifi, Icons.wifi),
            MaterialIconBuilder(AdaptiveIcons.zoom_in, Icons.zoom_in),
            MaterialIconBuilder(AdaptiveIcons.zoom_out, Icons.zoom_out),
            MaterialIconBuilder(AdaptiveIcons.archive, Icons.archive),
            MaterialIconBuilder(AdaptiveIcons.brush, Icons.brush),
            MaterialIconBuilder(
                AdaptiveIcons.calendar_month, Icons.calendar_month),
            MaterialIconBuilder(AdaptiveIcons.bar_chart, Icons.bar_chart),
            MaterialIconBuilder(
                AdaptiveIcons.airplanemode_active, Icons.airplanemode_active),
            MaterialIconBuilder(
                AdaptiveIcons.flip_camera_ios, Icons.flip_camera_ios),
            MaterialIconBuilder(AdaptiveIcons.flip_camera_ios_outlined,
                Icons.flip_camera_ios_outlined),
            MaterialIconBuilder(AdaptiveIcons.shopping_bag_outlined,
                Icons.shopping_bag_outlined),
            MaterialIconBuilder(AdaptiveIcons.shopping_bag, Icons.shopping_bag),
            MaterialIconBuilder(
                AdaptiveIcons.barcode_reader, Icons.barcode_reader),
            MaterialIconBuilder(AdaptiveIcons.king_bed, Icons.king_bed),
            MaterialIconBuilder(
                AdaptiveIcons.king_bed_outlined, Icons.king_bed_outlined),
            MaterialIconBuilder(
                AdaptiveIcons.currency_bitcoin, Icons.currency_bitcoin),
            MaterialIconBuilder(AdaptiveIcons.camera_alt, Icons.camera_alt),
            MaterialIconBuilder(
                AdaptiveIcons.camera_alt_outlined, Icons.camera_alt_outlined),
            MaterialIconBuilder(AdaptiveIcons.compass_calibration_outlined,
                Icons.compass_calibration_outlined),
            MaterialIconBuilder(
                AdaptiveIcons.compass_calibration, Icons.compass_calibration),
            MaterialIconBuilder(
                AdaptiveIcons.flag_outlined, Icons.flag_outlined),
            MaterialIconBuilder(
                AdaptiveIcons.folder_outlined, Icons.folder_outlined),
            MaterialIconBuilder(AdaptiveIcons.functions, Icons.functions),
            MaterialIconBuilder(AdaptiveIcons.grid_3x3, Icons.grid_3x3),
            MaterialIconBuilder(AdaptiveIcons.account_circle_outlined,
                Icons.account_circle_outlined),
            MaterialIconBuilder(
                AdaptiveIcons.account_circle, Icons.account_circle),
            MaterialIconBuilder(AdaptiveIcons.add_circle, Icons.add_circle),
            MaterialIconBuilder(
                AdaptiveIcons.add_circle_outline, Icons.add_circle_outline),
            MaterialIconBuilder(AdaptiveIcons.arrow_back, Icons.arrow_back),
            MaterialIconBuilder(AdaptiveIcons.battery_charging_full,
                Icons.battery_charging_full),
            MaterialIconBuilder(
                AdaptiveIcons.battery_alert, Icons.battery_alert),
            MaterialIconBuilder(
                AdaptiveIcons.bookmark_border, Icons.bookmark_border),
            MaterialIconBuilder(
                AdaptiveIcons.brightness_low, Icons.brightness_low),
            MaterialIconBuilder(
                AdaptiveIcons.brightness_high, Icons.brightness_high),
            MaterialIconBuilder(
                AdaptiveIcons.directions_bus, Icons.directions_bus),
            MaterialIconBuilder(
                AdaptiveIcons.directions_car, Icons.directions_car),
            MaterialIconBuilder(AdaptiveIcons.check_box_outline_blank_rounded,
                Icons.check_box_outline_blank_rounded),
            MaterialIconBuilder(AdaptiveIcons.indeterminate_check_box_outlined,
                Icons.indeterminate_check_box_outlined),
            MaterialIconBuilder(
                AdaptiveIcons.check_box_outlined, Icons.check_box_outlined),
            MaterialIconBuilder(AdaptiveIcons.check, Icons.check),
            MaterialIconBuilder(AdaptiveIcons.check_circle, Icons.check_circle),
            MaterialIconBuilder(
                AdaptiveIcons.check_circle_outline, Icons.check_circle_outline),
            MaterialIconBuilder(AdaptiveIcons.cancel, Icons.cancel),
            MaterialIconBuilder(AdaptiveIcons.watch_later, Icons.watch_later),
            MaterialIconBuilder(
                AdaptiveIcons.cloud_outlined, Icons.cloud_outlined),
            MaterialIconBuilder(AdaptiveIcons.cloud_download_outlined,
                Icons.cloud_download_outlined),
            MaterialIconBuilder(AdaptiveIcons.cloud_upload_outlined,
                Icons.cloud_upload_outlined),
            MaterialIconBuilder(
                AdaptiveIcons.chat_bubble_outline, Icons.chat_bubble_outline),
            MaterialIconBuilder(AdaptiveIcons.dehaze, Icons.dehaze),
            MaterialIconBuilder(
                AdaptiveIcons.delete_outline, Icons.delete_outline),
            MaterialIconBuilder(
                AdaptiveIcons.arrow_downward, Icons.arrow_downward),
            MaterialIconBuilder(AdaptiveIcons.edit, Icons.edit),
            MaterialIconBuilder(AdaptiveIcons.more_horiz, Icons.more_horiz),
            MaterialIconBuilder(AdaptiveIcons.error, Icons.error),
            MaterialIconBuilder(AdaptiveIcons.visibility_off_outlined,
                Icons.visibility_off_outlined),
            MaterialIconBuilder(
                AdaptiveIcons.visibility_off, Icons.visibility_off),
            MaterialIconBuilder(AdaptiveIcons.visibility, Icons.visibility),
            MaterialIconBuilder(AdaptiveIcons.favorite, Icons.favorite),
            MaterialIconBuilder(
                AdaptiveIcons.favorite_border, Icons.favorite_border),
            MaterialIconBuilder(
                AdaptiveIcons.arrow_forward, Icons.arrow_forward),
            MaterialIconBuilder(AdaptiveIcons.gamepad, Icons.gamepad),
            MaterialIconBuilder(AdaptiveIcons.games, Icons.games),
            MaterialIconBuilder(AdaptiveIcons.help, Icons.help),
            MaterialIconBuilder(AdaptiveIcons.help_outline, Icons.help_outline),
            MaterialIconBuilder(AdaptiveIcons.location_on, Icons.location_on),
            MaterialIconBuilder(AdaptiveIcons.mail_outline, Icons.mail_outline),
            MaterialIconBuilder(AdaptiveIcons.mic_none, Icons.mic_none),
            MaterialIconBuilder(AdaptiveIcons.lock_outline, Icons.lock_outline),
            MaterialIconBuilder(AdaptiveIcons.pets, Icons.pets),
            MaterialIconBuilder(
                AdaptiveIcons.person_outline, Icons.person_outline),
            MaterialIconBuilder(AdaptiveIcons.photo_library_outlined,
                Icons.photo_library_outlined),
            MaterialIconBuilder(
                AdaptiveIcons.photo_library, Icons.photo_library),
            MaterialIconBuilder(
                AdaptiveIcons.play_circle_outline, Icons.play_circle_outline),
            MaterialIconBuilder(AdaptiveIcons.remove, Icons.remove),
            MaterialIconBuilder(
                AdaptiveIcons.remove_circle, Icons.remove_circle),
            MaterialIconBuilder(AdaptiveIcons.remove_circle_outline,
                Icons.remove_circle_outline),
            MaterialIconBuilder(AdaptiveIcons.stars, Icons.stars),
            MaterialIconBuilder(AdaptiveIcons.label, Icons.label),
            MaterialIconBuilder(
                AdaptiveIcons.label_outline, Icons.label_outline),
            MaterialIconBuilder(AdaptiveIcons.thumb_down, Icons.thumb_down),
            MaterialIconBuilder(
                AdaptiveIcons.thumb_down_outlined, Icons.thumb_down_outlined),
            MaterialIconBuilder(AdaptiveIcons.thumb_up, Icons.thumb_up),
            MaterialIconBuilder(
                AdaptiveIcons.thumb_up_outlined, Icons.thumb_up_outlined),
            MaterialIconBuilder(AdaptiveIcons.schedule, Icons.schedule),
            MaterialIconBuilder(AdaptiveIcons.tram, Icons.tram),
            MaterialIconBuilder(AdaptiveIcons.arrow_upward, Icons.arrow_upward),
            MaterialIconBuilder(AdaptiveIcons.wifi_off, Icons.wifi_off),
            MaterialIconBuilder(AdaptiveIcons.exit_to_app, Icons.exit_to_app),
            MaterialIconBuilder(AdaptiveIcons.headset, Icons.headset),
            MaterialIconBuilder(AdaptiveIcons.heart_broken_outlined,
                Icons.heart_broken_outlined),
            MaterialIconBuilder(AdaptiveIcons.heart_broken, Icons.heart_broken),
            MaterialIconBuilder(
                AdaptiveIcons.hexagon_outlined, Icons.hexagon_outlined),
            MaterialIconBuilder(
                AdaptiveIcons.hourglass_bottom, Icons.hourglass_bottom),
            MaterialIconBuilder(AdaptiveIcons.house, Icons.house),
            MaterialIconBuilder(
                AdaptiveIcons.house_outlined, Icons.house_outlined),
            MaterialIconBuilder(AdaptiveIcons.list, Icons.list),
            MaterialIconBuilder(AdaptiveIcons.location_on, Icons.location_on),
            MaterialIconBuilder(AdaptiveIcons.location_off, Icons.location_off),
            MaterialIconBuilder(
                AdaptiveIcons.monetization_on, Icons.monetization_on),
            MaterialIconBuilder(AdaptiveIcons.monetization_on_outlined,
                Icons.monetization_on_outlined),
            MaterialIconBuilder(AdaptiveIcons.euro, Icons.euro),
            MaterialIconBuilder(
                AdaptiveIcons.currency_pound, Icons.currency_pound),
            MaterialIconBuilder(
                AdaptiveIcons.currency_ruble, Icons.currency_ruble),
            MaterialIconBuilder(AdaptiveIcons.currency_yen, Icons.currency_yen),
            MaterialIconBuilder(AdaptiveIcons.add_home, Icons.add_home),
            MaterialIconBuilder(AdaptiveIcons.add_link, Icons.add_link),
            MaterialIconBuilder(AdaptiveIcons.add_reaction, Icons.add_reaction),
            MaterialIconBuilder(AdaptiveIcons.album, Icons.album),
            MaterialIconBuilder(AdaptiveIcons.align_horizontal_center,
                Icons.align_horizontal_center),
            MaterialIconBuilder(AdaptiveIcons.align_horizontal_left,
                Icons.align_horizontal_left),
            MaterialIconBuilder(AdaptiveIcons.align_horizontal_right,
                Icons.align_horizontal_right),
            MaterialIconBuilder(AdaptiveIcons.align_vertical_bottom,
                Icons.align_vertical_bottom),
            MaterialIconBuilder(AdaptiveIcons.align_vertical_center,
                Icons.align_vertical_center),
            MaterialIconBuilder(
                AdaptiveIcons.align_vertical_top, Icons.align_vertical_top),
            MaterialIconBuilder(AdaptiveIcons.area_chart, Icons.area_chart),
            MaterialIconBuilder(AdaptiveIcons.aspect_ratio, Icons.aspect_ratio),
            MaterialIconBuilder(AdaptiveIcons.badge, Icons.badge),
            MaterialIconBuilder(AdaptiveIcons.bookmarks, Icons.bookmarks),
            MaterialIconBuilder(AdaptiveIcons.border_all, Icons.border_all),
            MaterialIconBuilder(AdaptiveIcons.cake, Icons.cake),
            MaterialIconBuilder(AdaptiveIcons.chat, Icons.chat),
            MaterialIconBuilder(
                AdaptiveIcons.closed_caption, Icons.closed_caption),
            MaterialIconBuilder(AdaptiveIcons.code, Icons.code),
            MaterialIconBuilder(AdaptiveIcons.coffee, Icons.coffee),
            MaterialIconBuilder(AdaptiveIcons.comment, Icons.comment),
            MaterialIconBuilder(AdaptiveIcons.compare, Icons.compare),
            MaterialIconBuilder(AdaptiveIcons.contrast, Icons.contrast),
            MaterialIconBuilder(AdaptiveIcons.copy, Icons.copy),
            MaterialIconBuilder(AdaptiveIcons.css, Icons.css),
            MaterialIconBuilder(AdaptiveIcons.cut, Icons.cut),
            MaterialIconBuilder(AdaptiveIcons.dialpad, Icons.dialpad),
            MaterialIconBuilder(AdaptiveIcons.diamond, Icons.diamond),
            MaterialIconBuilder(AdaptiveIcons.download, Icons.download),
            MaterialIconBuilder(AdaptiveIcons.edit_note, Icons.edit_note),
            MaterialIconBuilder(AdaptiveIcons.equalizer, Icons.equalizer),
            MaterialIconBuilder(AdaptiveIcons.event, Icons.event),
            MaterialIconBuilder(AdaptiveIcons.factory, Icons.factory),
            MaterialIconBuilder(AdaptiveIcons.fast_forward, Icons.fast_forward),
            MaterialIconBuilder(AdaptiveIcons.fax, Icons.fax),
            MaterialIconBuilder(AdaptiveIcons.feedback, Icons.feedback),
            MaterialIconBuilder(AdaptiveIcons.filter, Icons.filter),
            MaterialIconBuilder(AdaptiveIcons.fingerprint, Icons.fingerprint),
            MaterialIconBuilder(AdaptiveIcons.flash_auto, Icons.flash_auto),
            MaterialIconBuilder(AdaptiveIcons.flash_off, Icons.flash_off),
            MaterialIconBuilder(AdaptiveIcons.forum, Icons.forum),
            MaterialIconBuilder(AdaptiveIcons.gif, Icons.gif),
            MaterialIconBuilder(AdaptiveIcons.group_remove, Icons.group_remove),
            MaterialIconBuilder(AdaptiveIcons.highlight, Icons.highlight),
            MaterialIconBuilder(AdaptiveIcons.history, Icons.history),
            MaterialIconBuilder(AdaptiveIcons.hotel, Icons.hotel),
            MaterialIconBuilder(AdaptiveIcons.image_search, Icons.image_search),
            MaterialIconBuilder(AdaptiveIcons.inbox, Icons.inbox),
            MaterialIconBuilder(AdaptiveIcons.insights, Icons.insights),
            MaterialIconBuilder(AdaptiveIcons.line_style, Icons.line_style),
            MaterialIconBuilder(AdaptiveIcons.merge, Icons.merge),
            MaterialIconBuilder(AdaptiveIcons.message, Icons.message),
            MaterialIconBuilder(AdaptiveIcons.money, Icons.money),
            MaterialIconBuilder(AdaptiveIcons.more, Icons.more),
            MaterialIconBuilder(AdaptiveIcons.open_with, Icons.open_with),
            MaterialIconBuilder(AdaptiveIcons.padding, Icons.padding),
            MaterialIconBuilder(AdaptiveIcons.paste, Icons.paste),
            MaterialIconBuilder(AdaptiveIcons.pentagon, Icons.pentagon),
            MaterialIconBuilder(AdaptiveIcons.people, Icons.people),
            MaterialIconBuilder(AdaptiveIcons.phishing, Icons.phishing),
            MaterialIconBuilder(AdaptiveIcons.preview, Icons.preview),
            MaterialIconBuilder(AdaptiveIcons.print, Icons.print),
            MaterialIconBuilder(AdaptiveIcons.redo, Icons.redo),
            MaterialIconBuilder(AdaptiveIcons.repeat_one, Icons.repeat_one),
            MaterialIconBuilder(AdaptiveIcons.room, Icons.room),
            MaterialIconBuilder(AdaptiveIcons.save, Icons.save),
            MaterialIconBuilder(AdaptiveIcons.save_as, Icons.save_as),
            MaterialIconBuilder(AdaptiveIcons.savings, Icons.savings),
            MaterialIconBuilder(AdaptiveIcons.select_all, Icons.select_all),
            MaterialIconBuilder(AdaptiveIcons.sell, Icons.sell),
            MaterialIconBuilder(AdaptiveIcons.send, Icons.send),
            MaterialIconBuilder(AdaptiveIcons.shop, Icons.shop),
            MaterialIconBuilder(AdaptiveIcons.slideshow, Icons.slideshow),
            MaterialIconBuilder(AdaptiveIcons.snooze, Icons.snooze),
            MaterialIconBuilder(AdaptiveIcons.sort, Icons.sort),
            MaterialIconBuilder(AdaptiveIcons.source, Icons.source),
            MaterialIconBuilder(
                AdaptiveIcons.stacked_bar_chart, Icons.stacked_bar_chart),
            MaterialIconBuilder(
                AdaptiveIcons.stacked_line_chart, Icons.stacked_line_chart),
            MaterialIconBuilder(AdaptiveIcons.subscript, Icons.subscript),
            MaterialIconBuilder(AdaptiveIcons.sunny, Icons.sunny),
            MaterialIconBuilder(AdaptiveIcons.superscript, Icons.superscript),
            MaterialIconBuilder(AdaptiveIcons.sync, Icons.sync),
            MaterialIconBuilder(AdaptiveIcons.tab, Icons.tab),
            MaterialIconBuilder(AdaptiveIcons.tablet, Icons.tablet),
            MaterialIconBuilder(AdaptiveIcons.timeline, Icons.timeline),
            MaterialIconBuilder(AdaptiveIcons.title, Icons.title),
            MaterialIconBuilder(AdaptiveIcons.toll, Icons.toll),
            MaterialIconBuilder(AdaptiveIcons.train, Icons.train),
            MaterialIconBuilder(AdaptiveIcons.translate, Icons.translate),
            MaterialIconBuilder(AdaptiveIcons.turn_right, Icons.turn_right),
            MaterialIconBuilder(AdaptiveIcons.undo, Icons.undo),
            MaterialIconBuilder(AdaptiveIcons.unsubscribe, Icons.unsubscribe),
            MaterialIconBuilder(AdaptiveIcons.upload, Icons.upload),
            MaterialIconBuilder(AdaptiveIcons.usb, Icons.usb),
            MaterialIconBuilder(AdaptiveIcons.view_list, Icons.view_list),
            MaterialIconBuilder(AdaptiveIcons.warning, Icons.warning),
            MaterialIconBuilder(AdaptiveIcons.computer, Icons.computer),
            MaterialIconBuilder(AdaptiveIcons.insert_link, Icons.insert_link),
            MaterialIconBuilder(AdaptiveIcons.hearing, Icons.hearing),
            MaterialIconBuilder(AdaptiveIcons.home_filled, Icons.home_filled),
            MaterialIconBuilder(AdaptiveIcons.radio, Icons.radio),
            MaterialIconBuilder(AdaptiveIcons.update, Icons.update),
            MaterialIconBuilder(AdaptiveIcons.image, Icons.image),
            MaterialIconBuilder(AdaptiveIcons.menu, Icons.menu),
            MaterialIconBuilder(AdaptiveIcons.html, Icons.html),
            MaterialIconBuilder(
                AdaptiveIcons.playlist_play, Icons.playlist_play),
            MaterialIconBuilder(AdaptiveIcons.mouse, Icons.mouse),
            MaterialIconBuilder(AdaptiveIcons.smartphone, Icons.smartphone),
            MaterialIconBuilder(AdaptiveIcons.subtitles, Icons.subtitles),
            MaterialIconBuilder(
                AdaptiveIcons.library_music, Icons.library_music),
            MaterialIconBuilder(
                AdaptiveIcons.arrow_left_outlined, Icons.arrow_left_outlined),
            MaterialIconBuilder(
                AdaptiveIcons.arrow_right_outlined, Icons.arrow_right_outlined),
            MaterialIconBuilder(AdaptiveIcons.terminal, Icons.terminal),
            MaterialIconBuilder(AdaptiveIcons.monitor, Icons.monitor),
            MaterialIconBuilder(AdaptiveIcons.drag_handle, Icons.drag_handle),
            MaterialIconBuilder(AdaptiveIcons.wallpaper, Icons.wallpaper),
            MaterialIconBuilder(AdaptiveIcons.find_replace, Icons.find_replace),
            MaterialIconBuilder(AdaptiveIcons.key, Icons.key),
            MaterialIconBuilder(AdaptiveIcons.outbox, Icons.outbox),
            MaterialIconBuilder(AdaptiveIcons.window, Icons.window),
            MaterialIconBuilder(AdaptiveIcons.scanner, Icons.scanner),
            MaterialIconBuilder(AdaptiveIcons.storm, Icons.storm),
            MaterialIconBuilder(AdaptiveIcons.extension, Icons.extension),
          },
        );
}
