import 'package:fluent_ui/fluent_ui.dart';
import 'package:flutter_adaptive/flutter_adaptive.dart';
import 'flutter_adaptive_fluent_ui.dart';

class FluentUIIcons extends AdaptiveBundle {
  FluentUIIcons()
      : super(
          builders: {
            FluentUIIconBuilder(AdaptiveIcons.add, FluentIcons.add),
            FluentUIIconBuilder(AdaptiveIcons.add_home, FluentIcons.add_home),
            FluentUIIconBuilder(AdaptiveIcons.add_link, FluentIcons.add_link),
            FluentUIIconBuilder(
                AdaptiveIcons.add_reaction, FluentIcons.add_reaction),
            FluentUIIconBuilder(AdaptiveIcons.album, FluentIcons.album),
            FluentUIIconBuilder(AdaptiveIcons.align_horizontal_center,
                FluentIcons.align_horizontal_center),
            FluentUIIconBuilder(AdaptiveIcons.align_horizontal_left,
                FluentIcons.align_horizontal_left),
            FluentUIIconBuilder(AdaptiveIcons.align_horizontal_right,
                FluentIcons.align_horizontal_right),
            FluentUIIconBuilder(AdaptiveIcons.align_vertical_bottom,
                FluentIcons.align_vertical_bottom),
            FluentUIIconBuilder(AdaptiveIcons.align_vertical_center,
                FluentIcons.align_vertical_center),
            FluentUIIconBuilder(AdaptiveIcons.align_vertical_top,
                FluentIcons.align_vertical_top),
            FluentUIIconBuilder(AdaptiveIcons.archive, FluentIcons.archive),
            FluentUIIconBuilder(
                AdaptiveIcons.area_chart, FluentIcons.area_chart),
            FluentUIIconBuilder(
                AdaptiveIcons.aspect_ratio, FluentIcons.aspect_ratio),
            FluentUIIconBuilder(AdaptiveIcons.badge, FluentIcons.badge),
            FluentUIIconBuilder(AdaptiveIcons.bookmarks, FluentIcons.bookmarks),
            FluentUIIconBuilder(
                AdaptiveIcons.border_all, FluentIcons.border_all),
            FluentUIIconBuilder(AdaptiveIcons.brush, FluentIcons.brush),
            FluentUIIconBuilder(AdaptiveIcons.build, FluentIcons.build),
            FluentUIIconBuilder(AdaptiveIcons.cake, FluentIcons.cake),
            FluentUIIconBuilder(AdaptiveIcons.camera, FluentIcons.camera),
            FluentUIIconBuilder(AdaptiveIcons.cancel, FluentIcons.cancel),
            FluentUIIconBuilder(AdaptiveIcons.chat, FluentIcons.chat),
            FluentUIIconBuilder(
                AdaptiveIcons.chevron_left, FluentIcons.chevron_left),
            FluentUIIconBuilder(
                AdaptiveIcons.chevron_right, FluentIcons.chevron_right),
            FluentUIIconBuilder(AdaptiveIcons.clear, FluentIcons.clear),
            FluentUIIconBuilder(
                AdaptiveIcons.closed_caption, FluentIcons.closed_caption),
            FluentUIIconBuilder(AdaptiveIcons.cloud, FluentIcons.cloud),
            FluentUIIconBuilder(
                AdaptiveIcons.cloud_download, FluentIcons.cloud_download),
            FluentUIIconBuilder(
                AdaptiveIcons.cloud_upload, FluentIcons.cloud_upload),
            FluentUIIconBuilder(AdaptiveIcons.code, FluentIcons.code),
            FluentUIIconBuilder(AdaptiveIcons.coffee, FluentIcons.coffee),
            FluentUIIconBuilder(AdaptiveIcons.comment, FluentIcons.comment),
            FluentUIIconBuilder(AdaptiveIcons.compare, FluentIcons.compare),
            FluentUIIconBuilder(AdaptiveIcons.contrast, FluentIcons.contrast),
            FluentUIIconBuilder(AdaptiveIcons.copy, FluentIcons.copy),
            FluentUIIconBuilder(AdaptiveIcons.crop, FluentIcons.crop),
            FluentUIIconBuilder(AdaptiveIcons.css, FluentIcons.css),
            FluentUIIconBuilder(AdaptiveIcons.cut, FluentIcons.cut),
            FluentUIIconBuilder(AdaptiveIcons.delete, FluentIcons.delete),
            FluentUIIconBuilder(AdaptiveIcons.dialpad, FluentIcons.dialpad),
            FluentUIIconBuilder(AdaptiveIcons.diamond, FluentIcons.diamond),
            FluentUIIconBuilder(AdaptiveIcons.download, FluentIcons.download),
            FluentUIIconBuilder(AdaptiveIcons.edit, FluentIcons.edit),
            FluentUIIconBuilder(AdaptiveIcons.edit_note, FluentIcons.edit_note),
            FluentUIIconBuilder(AdaptiveIcons.equalizer, FluentIcons.equalizer),
            FluentUIIconBuilder(AdaptiveIcons.error, FluentIcons.error),
            FluentUIIconBuilder(AdaptiveIcons.event, FluentIcons.event),
            FluentUIIconBuilder(AdaptiveIcons.factory, FluentIcons.factory),
            FluentUIIconBuilder(
                AdaptiveIcons.fast_forward, FluentIcons.fast_forward),
            FluentUIIconBuilder(AdaptiveIcons.fax, FluentIcons.fax),
            FluentUIIconBuilder(AdaptiveIcons.feedback, FluentIcons.feedback),
            FluentUIIconBuilder(AdaptiveIcons.filter, FluentIcons.filter),
            FluentUIIconBuilder(
                AdaptiveIcons.fingerprint, FluentIcons.fingerprint),
            FluentUIIconBuilder(AdaptiveIcons.flag, FluentIcons.flag),
            FluentUIIconBuilder(
                AdaptiveIcons.flash_auto, FluentIcons.flash_auto),
            FluentUIIconBuilder(AdaptiveIcons.flash_off, FluentIcons.flash_off),
            FluentUIIconBuilder(AdaptiveIcons.folder, FluentIcons.folder),
            FluentUIIconBuilder(
                AdaptiveIcons.folder_open, FluentIcons.folder_open),
            FluentUIIconBuilder(AdaptiveIcons.forum, FluentIcons.forum),
            FluentUIIconBuilder(AdaptiveIcons.forward, FluentIcons.forward),
            FluentUIIconBuilder(AdaptiveIcons.gif, FluentIcons.gif),
            FluentUIIconBuilder(AdaptiveIcons.group, FluentIcons.group),
            FluentUIIconBuilder(
                AdaptiveIcons.group_remove, FluentIcons.group_remove),
            FluentUIIconBuilder(AdaptiveIcons.headset, FluentIcons.headset),
            FluentUIIconBuilder(
                AdaptiveIcons.heart_broken, FluentIcons.heart_broken),
            FluentUIIconBuilder(AdaptiveIcons.help, FluentIcons.help),
            FluentUIIconBuilder(AdaptiveIcons.hexagon, FluentIcons.hexagon),
            FluentUIIconBuilder(AdaptiveIcons.highlight, FluentIcons.highlight),
            FluentUIIconBuilder(AdaptiveIcons.history, FluentIcons.history),
            FluentUIIconBuilder(AdaptiveIcons.home, FluentIcons.home),
            FluentUIIconBuilder(AdaptiveIcons.hotel, FluentIcons.hotel),
            FluentUIIconBuilder(
                AdaptiveIcons.image_search, FluentIcons.image_search),
            FluentUIIconBuilder(AdaptiveIcons.inbox, FluentIcons.inbox),
            FluentUIIconBuilder(AdaptiveIcons.info, FluentIcons.info),
            FluentUIIconBuilder(AdaptiveIcons.insights, FluentIcons.insights),
            FluentUIIconBuilder(AdaptiveIcons.label, FluentIcons.label),
            FluentUIIconBuilder(AdaptiveIcons.light, FluentIcons.light),
            FluentUIIconBuilder(AdaptiveIcons.lightbulb, FluentIcons.lightbulb),
            FluentUIIconBuilder(
                AdaptiveIcons.line_style, FluentIcons.line_style),
            FluentUIIconBuilder(AdaptiveIcons.link, FluentIcons.link),
            FluentUIIconBuilder(AdaptiveIcons.list, FluentIcons.list),
            FluentUIIconBuilder(AdaptiveIcons.lock, FluentIcons.lock),
            FluentUIIconBuilder(AdaptiveIcons.mail, FluentIcons.mail),
            FluentUIIconBuilder(AdaptiveIcons.merge, FluentIcons.merge),
            FluentUIIconBuilder(AdaptiveIcons.message, FluentIcons.message),
            FluentUIIconBuilder(AdaptiveIcons.mic_off, FluentIcons.mic_off),
            FluentUIIconBuilder(AdaptiveIcons.money, FluentIcons.money),
            FluentUIIconBuilder(AdaptiveIcons.more, FluentIcons.more),
            FluentUIIconBuilder(
                AdaptiveIcons.music_note, FluentIcons.music_note),
            FluentUIIconBuilder(AdaptiveIcons.open_with, FluentIcons.open_with),
            FluentUIIconBuilder(AdaptiveIcons.padding, FluentIcons.padding),
            FluentUIIconBuilder(AdaptiveIcons.paste, FluentIcons.paste),
            FluentUIIconBuilder(AdaptiveIcons.pause, FluentIcons.pause),
            FluentUIIconBuilder(AdaptiveIcons.pentagon, FluentIcons.pentagon),
            FluentUIIconBuilder(AdaptiveIcons.people, FluentIcons.people),
            FluentUIIconBuilder(AdaptiveIcons.phishing, FluentIcons.phishing),
            FluentUIIconBuilder(AdaptiveIcons.phone, FluentIcons.phone),
            FluentUIIconBuilder(AdaptiveIcons.photo, FluentIcons.photo),
            FluentUIIconBuilder(AdaptiveIcons.pin, FluentIcons.pin),
            FluentUIIconBuilder(AdaptiveIcons.preview, FluentIcons.preview),
            FluentUIIconBuilder(AdaptiveIcons.print, FluentIcons.print),
            FluentUIIconBuilder(AdaptiveIcons.redo, FluentIcons.redo),
            FluentUIIconBuilder(AdaptiveIcons.refresh, FluentIcons.refresh),
            FluentUIIconBuilder(AdaptiveIcons.remove, FluentIcons.remove),
            FluentUIIconBuilder(
                AdaptiveIcons.repeat_one, FluentIcons.repeat_one),
            FluentUIIconBuilder(AdaptiveIcons.reply, FluentIcons.reply),
            FluentUIIconBuilder(AdaptiveIcons.reply_all, FluentIcons.reply_all),
            FluentUIIconBuilder(AdaptiveIcons.rocket, FluentIcons.rocket),
            FluentUIIconBuilder(AdaptiveIcons.room, FluentIcons.room),
            FluentUIIconBuilder(AdaptiveIcons.save, FluentIcons.save),
            FluentUIIconBuilder(AdaptiveIcons.save_as, FluentIcons.save_as),
            FluentUIIconBuilder(AdaptiveIcons.savings, FluentIcons.savings),
            FluentUIIconBuilder(AdaptiveIcons.search, FluentIcons.search),
            FluentUIIconBuilder(
                AdaptiveIcons.select_all, FluentIcons.select_all),
            FluentUIIconBuilder(AdaptiveIcons.sell, FluentIcons.sell),
            FluentUIIconBuilder(AdaptiveIcons.send, FluentIcons.send),
            FluentUIIconBuilder(AdaptiveIcons.settings, FluentIcons.settings),
            FluentUIIconBuilder(AdaptiveIcons.share, FluentIcons.share),
            FluentUIIconBuilder(AdaptiveIcons.shield, FluentIcons.shield),
            FluentUIIconBuilder(AdaptiveIcons.shop, FluentIcons.shop),
            FluentUIIconBuilder(
                AdaptiveIcons.shopping_cart, FluentIcons.shopping_cart),
            FluentUIIconBuilder(AdaptiveIcons.slideshow, FluentIcons.slideshow),
            FluentUIIconBuilder(AdaptiveIcons.snooze, FluentIcons.snooze),
            FluentUIIconBuilder(AdaptiveIcons.sort, FluentIcons.sort),
            FluentUIIconBuilder(AdaptiveIcons.source, FluentIcons.source),
            FluentUIIconBuilder(
                AdaptiveIcons.stacked_bar_chart, FluentIcons.stacked_bar_chart),
            FluentUIIconBuilder(AdaptiveIcons.stacked_line_chart,
                FluentIcons.stacked_line_chart),
            FluentUIIconBuilder(AdaptiveIcons.stop, FluentIcons.stop),
            FluentUIIconBuilder(AdaptiveIcons.subscript, FluentIcons.subscript),
            FluentUIIconBuilder(AdaptiveIcons.sunny, FluentIcons.sunny),
            FluentUIIconBuilder(
                AdaptiveIcons.superscript, FluentIcons.superscript),
            FluentUIIconBuilder(AdaptiveIcons.sync, FluentIcons.sync),
            FluentUIIconBuilder(AdaptiveIcons.tab, FluentIcons.tab),
            FluentUIIconBuilder(AdaptiveIcons.tablet, FluentIcons.tablet),
            FluentUIIconBuilder(AdaptiveIcons.tag, FluentIcons.tag),
            FluentUIIconBuilder(AdaptiveIcons.timeline, FluentIcons.timeline),
            FluentUIIconBuilder(AdaptiveIcons.timer, FluentIcons.timer),
            FluentUIIconBuilder(AdaptiveIcons.title, FluentIcons.title),
            FluentUIIconBuilder(AdaptiveIcons.toll, FluentIcons.toll),
            FluentUIIconBuilder(AdaptiveIcons.train, FluentIcons.train),
            FluentUIIconBuilder(AdaptiveIcons.translate, FluentIcons.translate),
            FluentUIIconBuilder(
                AdaptiveIcons.turn_right, FluentIcons.turn_right),
            FluentUIIconBuilder(AdaptiveIcons.umbrella, FluentIcons.umbrella),
            FluentUIIconBuilder(AdaptiveIcons.undo, FluentIcons.undo),
            FluentUIIconBuilder(
                AdaptiveIcons.unsubscribe, FluentIcons.unsubscribe),
            FluentUIIconBuilder(AdaptiveIcons.upload, FluentIcons.upload),
            FluentUIIconBuilder(AdaptiveIcons.usb, FluentIcons.usb),
            FluentUIIconBuilder(AdaptiveIcons.view_list, FluentIcons.view_list),
            FluentUIIconBuilder(AdaptiveIcons.warning, FluentIcons.warning),
            FluentUIIconBuilder(AdaptiveIcons.archive, FluentIcons.archive),
            FluentUIIconBuilder(
                AdaptiveIcons.calendar_month, FluentIcons.calendar),
            FluentUIIconBuilder(
                AdaptiveIcons.bar_chart, FluentIcons.bar_chart4),
            FluentUIIconBuilder(
                AdaptiveIcons.chat_bubble, FluentIcons.chat_solid),
            FluentUIIconBuilder(AdaptiveIcons.check, FluentIcons.check_mark),
            FluentUIIconBuilder(AdaptiveIcons.clear, FluentIcons.clear),
            FluentUIIconBuilder(AdaptiveIcons.cloud, FluentIcons.cloud),
            FluentUIIconBuilder(AdaptiveIcons.person, FluentIcons.contact),
          },
        );
}
