import 'package:flutter/material.dart';
import 'package:flutter_adaptive_core/flutter_adaptive_core.dart';

class MaterialTextInputBuilder
    extends AdaptiveWidgetBuilder<AdaptiveTextInput> {
  @override
  Widget build(BuildContext context, AdaptiveTextInput component) {
    return TextField(
      decoration: InputDecoration(
        border: const OutlineInputBorder(),
        labelText: component.placeholder,
      ),
      controller: component.controller,
      onChanged: component.onChanged,
      // groupId = EditableText,
      // controller,
      focusNode: component.focusNode,
      // undoController,
      keyboardType: component.keyboardType,
      textInputAction: component.textInputAction,
      textCapitalization: component.textCapitalization,
      style: component.style,
      strutStyle: component.strutStyle,
      textAlign: component.textAlign,
      textAlignVertical: component.textAlignVertical,
      // textDirection,
      readOnly: component.readOnly,
      // @Deprecated(
      //   'Use `contextMenuBuilder` instead. '
      //   'This feature was deprecated after v3.3.0-0.5.pre.',
      // )
      // toolbarOptions,
      showCursor: component.showCursor,
      autofocus: component.autofocus,
      // statesController,
      obscuringCharacter: component.obscuringCharacter,
      obscureText: component.obscureText,
      autocorrect: component.autocorrect,
      smartDashesType: component.smartDashesType,
      smartQuotesType: component.smartQuotesType,
      enableSuggestions: component.enableSuggestions,
      maxLines: component.maxLines,
      minLines: component.minLines,
      expands: component.expands,
      maxLength: component.maxLength,
      maxLengthEnforcement: component.maxLengthEnforcement,
      onEditingComplete: component.onEditingComplete,
      onSubmitted: component.onSubmitted,
      // onAppPrivateCommand,
      inputFormatters: component.inputFormatters,
      enabled: component.enabled,
      // ignorePointers,
      cursorWidth: component.cursorWidth,
      cursorHeight: component.cursorHeight,
      cursorRadius: component.cursorRadius,
      // cursorOpacityAnimates,
      cursorColor: component.cursorColor,
      // cursorErrorColor,
      selectionHeightStyle: component.selectionHeightStyle,
      selectionWidthStyle: component.selectionWidthStyle,
      keyboardAppearance: component.keyboardAppearance,
      scrollPadding: component.scrollPadding,
      dragStartBehavior: component.dragStartBehavior,
      enableInteractiveSelection: component.enableInteractiveSelection,
      selectionControls: component.selectionControls,
      onTap: component.onTap,
      // onTapAlwaysCalled = false,
      // onTapOutside,
      // mouseCursor,
      // buildCounter,
      scrollController: component.scrollController,
      scrollPhysics: component.scrollPhysics,
      autofillHints: component.autofillHints,
      // contentInsertionConfiguration,
      // clipBehavior = Clip.hardEdge,
      restorationId: component.restorationId,
      // scribbleEnabled = true,
      // enableIMEPersonalizedLearning = true,
      contextMenuBuilder: component.contextMenuBuilder,
      // canRequestFocus = true,
      // spellCheckConfiguration,
      // magnifierConfiguration,
    );
  }
}
